[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = ""
authors = ["labidahrom <labidahrom@yandex.ru>"]
readme = "README.md"
packages = [{include = "gendiff"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
gendiff = "gendiff.scripts.gendiff:generate_diff"
